<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>UPDOWN_TOOL</RootNamespace>
    <StartupObject>UPDOWN_TOOL.Program</StartupObject>
  </PropertyGroup>

</Project>
